#let background = rgb("#e0dcd3")
#let content = rgb("#6e8771")
#let content-highlight = rgb("#dbbc7f93")
#let content-reference-link = rgb("#6693ba")
#let theorem-background = rgb("#b0c9cea4")
#let definition-background = rgb("#b4ceb77f")